### ISSUE TITLE
on EOF, can I get a list of tokens that would be matched given more input?

### ISSUE THREAD

**Issue by akonsu** [no-context/moo#101]
When the lexer encounters EOF, and ends in a valid (finite state machine) state, is it possible to get a list of tokens that are "incomplete", meaning that the lexer just matched a prefix and stopped when it found a EOF?

I mean, say, I define these tokens:

"abc"
"abd"
"cde"

and the input is "ab". When the lexer sees EOF, I need to get a list with two tokens "abc" and "abd". In the case where input has invalid characters the list would be empty. For example, for input "abe", there are no tokens that are incomplete. I need this for content assist in my editor.

**Comment by nathan** [comment]
The list isn't necessarily finite (e.g., `/ab.+/`), and this would require parsing regexes. You're probably best off matching `/\w+/` (or some other appropriate catch-all) at the end of your list of tokens and generating the completion list on your own.

**Comment by akonsu** [comment]
@tjvr I understand. Thanks for your response. This is not for completions, BTW. It is for syntax highlighting. For example, I want to highlight strings, as the user types them, and even if they are still incomplete. Or comments, etc.

**Comment by nathan** [comment]
> @tjvr I understand. Thanks for your response. This is not for completions, BTW. It is for syntax highlighting. For example, I want to highlight strings, as the user types them, and even if they are still incomplete. Or comments, etc.

You may want to write your lexer such that every token type matches its prefixes too (e.g., strings match unmatched `"…` to EOL/EOF). Then you can just use the token stream as-is, which is much easier than trying to re-lex the end token after you recover it.
