### ISSUE TITLE
Latest version not pushed to npm

### ISSUE THREAD

**Issue by TheMrZZ** [no-context/moo#110]
It seems that the last version is not pushed on npm.
In the latest npm version, the moo exports are the following:

```js
return {
    compile: compile,
    states: compileStates,
    error: Object.freeze({error: true}),
  }
```

while in the github repo, they are the following:
```js
  return {
    compile: compile,
    states: compileStates,
    error: Object.freeze({error: true}),
    fallback: Object.freeze({fallback: true}),
    keywords: keywordTransform,
}
```

The npm repo mentions the existence of built-in `moo.keywords`, but they are not available via `npm i moo` - therefore, I think the latest version has not been pushed on npm.

I tried to uninstall / install, update, rebuild etc... Nothing seemed to work.
Am I doing something wrong?

**Comment by tjvr** [comment]
That's correct, we haven't done an NPM release for a while! I was waiting for the API changes to settle down a bit. I should probably do one this week :blush:

**Comment by TheMrZZ** [comment]
Fine :) thank you for your quick answer!

**Comment by tjvr** [comment]
This is now [published to NPM](https://github.com/no-context/moo/releases/tag/v0.5.0). Thanks for the reminder! :blush:
