### ISSUE TITLE
Advice on Moo / Nearley usage

### ISSUE THREAD

**Issue by GreenImp** [no-context/moo#134]
Hi,

I'm trying to get to grips with using Nearley.js and Moo together, and I'm finding it a bit difficult to figure out how to build a tokenizer to do what I want.

The code examples I'm working on are a bit large, and the explanation is  a bit long. Is there any chance that I could have a chat over email to try and help?
I did email @tjvr but not sure if he's seen it. If he's too busy, @nathan would you mind having a chat?

**Comment by mspoulsen** [comment]
I also wish there we a guide of some sort. Really difficult to get started or even understanding why I would need Moo to begin with? I have heard that ambiguities are better handled with a lexer so I am curious about Moo.

A few easy to understand examples would be nice :slightly_smiling_face:

**Comment by mspoulsen** [comment]
I found this video which was really helpful: https://www.youtube.com/watch?v=GP91_duEmk8

**Comment by tjvr** [comment]
I think this question would probably be better on the Nearley repository :-)
