### ISSUE TITLE
Maybe a minified moo.js file?

### ISSUE THREAD

**Issue by gosoccerboy5** [no-context/moo#160]
So people don't have to worry as much about filesize when importing the file

**Comment by tjvr** [comment]
I’m afraid we’re not planning to maintain a minified JS file. Of course you can minify it yourself, perhaps as part of a build process bundling and minifying your whole application.

**Comment by gosoccerboy5** [comment]
Blobby tables replied to my issue!! yay
Thanks for responding btw
