### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by alexbalonperin** [no-context/moo#179]
Hello,

First of all, thank you for the awesome library. :100: 

I am not sure if this is appropriate to make an issue for this but I would like to ask if a new version of moo.js could be packaged and released. The latest available release seems to be from 2019 and since then there has been at least one change that would greatly help us in production. Namely, the change related to content security policy. At the moment, we are going to copy and paste the whole moo.js source code in our codebase to get the change quickly so that we can use the library at all (it's a dependency of pgsql-ast-parser). We are a bit pressed by time but of course I would prefer to avoid having to c&p the source code of moo.js or fork it and publish our own version. Benefiting from future changes from the great contributors of this library would be awesome.

Thank you so much.  :bow:

**Comment by tjvr** [comment]
:heavy_check_mark: That's done! <https://github.com/no-context/moo/releases/tag/v0.5.2>
