### ISSUE TITLE
Keyword order

### ISSUE THREAD

**Issue by andraaspar** [no-context/moo#180]
In #159 @tjvr mentioned that moo relies on the order that keys are retrieved from a JavaScript object. That's unexpected... I thought the order of keys in a JavaScript object was undefined as per the spec and so this really surprised me. Looking into it, I see that [since ES2015 there is an order specified in the spec](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order/38218582), albeit a complicated one.

It would be best to spell out this feature in the documentation, or, maybe, since the order is significant, moo should use an array instead of an object:

```JS
moo.compile({
  TERM: /[a-z]+/,
  PREFIXTERM: /\*|(?:[a-z]+\*)/,
})
```

would become:

```JS
moo.compile([
  ["TERM", /[a-z]+/],
  ["PREFIXTERM", /\*|(?:[a-z]+\*)/],
])
```

And that would be explicit about the order being significant.

**Comment by nathan** [comment]
> complicated

As long as you're not using very weird (i.e. integer, symbol, or duplicated) token names, the order has always been the order they appear in the source code, even before this was required by the specification.

If using basic language features makes you uncomfortable, moo already accepts an array of rules:
```js
moo.compile([
  {type: 'TERM', match: /[a-z]+/},
  {type: 'PREFIXTERM', match: /\*|(?:[a-z]+\*)/},
])
```

This should probably be documented.

**Comment by andraaspar** [comment]
@nathan Thank you for taking the time to answer my question. That snippet is exactly the thing I was looking for.

> If using basic language features makes you uncomfortable

I am sorry if I offended you somehow.

**Comment by nathan** [comment]
I suppose you could do
```js
const IDENT = moo.keywords({
  KW: ['while', 'if', 'else', 'moo', 'cows'],
})
moo.compile([
  {match: /[a-zA-Z]+/, type: t => IDENT(t) || 'IDENT'},
  {match: /\s+/, lineBreaks: true, type: 'SPACE'},
])
```
but unless you actually have multiple rules for the same type that can't be combined, just use an object. Array rules are more verbose, harder to read, and exactly equivalent to object rules.

@tjvr is there a reason we don't accept `defaultType` vel sim. in array rules?

**Comment by tjvr** [comment]
Do we not? A quick glance at the code suggests we do 🤔

**Comment by nathan** [comment]
Oops, we do. My mistake.
