### ISSUE TITLE
Consider ignoreCase for keywords

### ISSUE THREAD

**Issue by tjvr** [no-context/moo#67]
[Previously](https://github.com/tjvr/moo/issues/46), [previously](https://github.com/tjvr/moo/issues/53).

**Comment by nathan** [comment]
How would this work design-wise? Would moo fold the case itself, e.g., `'const'` => `/[cC][oO][nN][sS][tT]/`? (If so, it should probably support Unicode)

**Comment by tjvr** [comment]
> Would moo fold the case itself

Yes, it would have to.

(I saw a proposal somewhere for inline flag modifiers—`(?i…)` perhaps?—but fairly obviously that's not something Moo can rely on! :-) )

**Comment by camullen** [comment]
I created a pull request for this: #78

**Comment by tjvr** [comment]
We now support general-purpose `type` transforms.
