### ISSUE TITLE
Skip tokens

### ISSUE THREAD

**Issue by notsonotso** [no-context/moo#71]
During iteration, it would be great to be able to skip certain tokens, such as white space and comments.

In ANTLR, this is done using "hidden" channels. Maybe something like a "skip" attribute?

    {match: /\s+/, lineBreaks: true; skip: true}

**Comment by Hardmath123** [comment]
@tjvr this sounds like a moo question.

**Comment by tjvr** [comment]
See #24.

**Comment by notsonotso** [comment]
@tjvr I don't like that solution. A skip property would be very useful.

**Comment by tjvr** [comment]
Well, I don't like your solution. We've decided that such a feature would be out of scope for moo.

**Comment by notsonotso** [comment]
@tjvr no problem, I forked moo and implemented it.
