### ISSUE TITLE
Bugs in the impl

### ISSUE THREAD

**Issue by notsonotso** [no-context/moo#72]
https://github.com/no-context/moo/blob/master/moo.js#L258

    throw new Error('keyword type must be string: ' + name)

The identifier `name` doesn't exist.

Also, https://github.com/no-context/moo/blob/master/moo.js#L395, where variable `nl` depends on a variable hoisted from a block above. Not a bug per se, but truly ugly.

**Comment by tjvr** [comment]
> The identifier name doesn't exist.

Thanks. Fixed in fd9210c.

> truly ugly.

There's really no need to be rude.

**Comment by notsonotso** [comment]
@tjvr not rude at all, just an observation

**Comment by nathan** [comment]
@notsonotso

> not rude at all, just an observation

You called someone else's work "truly **ugly**":

> **ugly** |ˈəɡli|
> 
> unpleasant or repulsive, especially in appearance

That is rude. If you meant "error-prone," say "error-prone," and stop being vitriolic just to annoy people.
