### ISSUE TITLE
How can I ignore tokens?

### ISSUE THREAD

**Issue by Ghabriel** [no-context/moo#81]
I'm using moo + nearley and I want to support comments (//... and /* ... */) in arbitrary places without polluting my grammar. How can I achieve this?

**Comment by tjvr** [comment]
Moo doesn’t support this by design, but you can wrap the lexer yourself to do whatever you want.

Perhaps try replacing your Lexer’s `next()` method?

```js
lexer.next = (next => {
let tok
while ((tok = next()) && toktype === ‘comment’) {}
return tok
})(lexer.next)
```

(Untested; I only just came up with this!)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ghabriel** [comment]
This works:
```javascript
lexer.next = (next => () => {
    let tok;
    while ((tok = next.call(lexer)) && tok.type === "comment") {}
    return tok;
})(lexer.next);
```

However, things like `cla/*comment*/ss` become `cla` and `ss` instead of `class`. I don't think wrapping the lexer can solve this specific case without basically reimplementing the entire lexer, can it?

However, for most cases this version is enough, so thanks for your help!

**Comment by bd82** [comment]
Ignored tokens in most languages I am aware of are not normally treated as if they did not exist
instead they are not passed to the parser and can still be used as "separators"
imagine whitespace:

"public static class Foo extends Bar..."
Whitespace is ignored in Java, but this is not read a **single** huge identifier:
"publicstaticclassFooextendsBar"

**Comment by Ghabriel** [comment]
I initially thought that comments were in fact treated as if they didn't exist (I was aware about whitespaces, though), but I ran some tests and indeed every language I've tried showed a syntax error with things like `cla/*comment*/ss`. I'll close this issue, thanks everyone!

**Comment by tjvr** [comment]
> This works

Thanks for correcting my example; I was typing on a phone.

I’m glad this works. I can’t imagine how you’d implement a lexer which worked the other way; and it would probably not be efficient! :-) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
