### ISSUE TITLE
README has misleading documentation for states?

### ISSUE THREAD

**Issue by JoshuaGrams** [no-context/moo#97]
"It's also nice to let states inherit rules from other states" but `push` replaces the entire regex, it doesn't add to it.  Also "pop returns to a previous state, by removing one or more states from the stack" but I don't see any code path to do more than a single pop.

Am I missing something?  I don't have a need or use-case for either of those things, but the docs preferably shouldn't confuse people by claiming features that aren't present or mis-describing ones that are...

**Comment by nathan** [comment]
Yeah, that states paragraph includes a great description of [this feature which hasn't been merged yet and has little to do with `push`/`pop`](https://github.com/no-context/moo/pull/93). I guess @tjvr meant you can inherit all rules and change the transition behavior, so there are implicitly `main-pop-to-main` and `main-pop-to-lit` states?

[This line](https://github.com/no-context/moo/blob/93ccdb8c76b0966b05d1488c9a0cafa9a04366ed/moo.js#L203) exists so in the future we can support `pop: 2` or `pop: 'aStateName'`, but the README should probably reflect the present state of affairs. The only currently permitted values are `1`, `true`, and some strings/`valueOf`-objects if you want to be pedantic about it.

**Comment by tjvr** [comment]
I rewrote the readme for states in #100; hopefully that clears things up.e

Thanks for your question! :smiley:
